Разметка главной страницы
htmlacademy-htmlcss/1789677-nerds-31 pull request #2
Opened 2021-05-21 06:52 UTC by blessMe-Padre

2021-05-23 10:51 UTC, mikhin commented
В консоли есть ошибки, давай их уберем?)

<img width="1271" alt="Screenshot 2021-05-23 at 13 50 50" src="https://user-images.githubusercontent.com/38258318/119257435-ee8f7180-bbcd-11eb-8013-4f5472e9df27.png">

2021-05-23 19:19 UTC, mikhin requested changes

2021-05-23 19:19 UTC, mikhin commented on index.html
> +        <p>Долго, дорого, скрупулезно.</p>
А это может быть заголовком? Если да, то тогда и скрытый не нужен)

2021-05-23 19:19 UTC, mikhin commented on index.html
> +            <h3 class="services__title">Веб-сайты</h3>
Если по БЭМ то тогда чуть правильнее будет `__item-title`

2021-05-23 19:19 UTC, mikhin commented on index.html
> +            <a href="#" class="button btn--green">Заказать</a>
`button btn--green` в такой нотации `btn--green` не может быть БЭМ-модификатором класса `button` — нужно написать их однотипно)

2021-05-23 19:19 UTC, mikhin commented on index.html
> +      <h2 class=".visually-hidden">Производители</h2>
Точка лишняя)

2021-05-25 01:57 UTC, blessMe-Padre commented on blank.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
Это осталось из предыдущего файла. Забыл удалить (делал еще до 2 лайва). Удалил)

2021-05-25 02:05 UTC, blessMe-Padre commented on blank.html
> +    <section>
Я не совсем понял для чего делать 2 секции внутри футера, но на лайве так показали( Исправил на  просто дивы

2021-05-25 02:07 UTC, blessMe-Padre commented on blank.html
> +    <p> Ошибка, такой страницы не существует =(</p>
Спасибо! Невнимательный. Исправил

2021-05-25 02:12 UTC, blessMe-Padre commented on blank.html
> +    <section>
исправил на дивы

2021-05-25 02:14 UTC, blessMe-Padre commented on blank.html
> +  <link rel="stylesheet" type="text/css" href="css/style.css">
Исправил
Оставил только 
  <meta charset="UTF-8">
  <title>HTML Academy: Нёрдс</title>

2021-05-25 02:15 UTC, blessMe-Padre commented on blank.html
> +  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
Исправил)

2021-05-25 02:20 UTC, blessMe-Padre commented on catalog.html
> +      <a href="index.html">
А я подумал должен)) Ведь он же является и ссылкой для перехода на главную. Получается мне нужно вынести лого и корзину за nav?

2021-05-25 02:24 UTC, blessMe-Padre commented on catalog.html
> +      <a href="blank.html">Корзина</a>
Исправил. Вынес лого и корзину из навигации

2021-05-25 02:30 UTC, blessMe-Padre commented on catalog.html
> +    <section>
Думал туда h1 заголовок поставить.  
Исправил.

2021-05-25 02:31 UTC, blessMe-Padre commented on catalog.html
> +      <section>
Исправил на дивы

2021-05-25 02:34 UTC, blessMe-Padre commented on catalog.html
> +            <input type="range" min="0" max="15000" value="10000"> <br>
Исправил)

2021-05-25 02:37 UTC, blessMe-Padre commented on catalog.html
> +                <input type="radio" name="adaptive" value="adaptive" id="filter-adaptive" checked>
Спасибо, исправил. Посмотрел гайд как сделать css слайдер и кажется разобрался)

2021-05-25 02:38 UTC, blessMe-Padre commented on catalog.html
> +              <input type="checkbox" name="filter-slider" id="filter-slider" checked>
исправил

2021-05-25 02:39 UTC, blessMe-Padre commented on catalog.html
> +      <h2>готовые шаблоны</h2>
исправил, невнимательность))

2021-05-25 02:44 UTC, blessMe-Padre commented on catalog.html
> +        <li>По цене</li>
это я не продумал. Обернул в ссылки элементы

2021-05-25 02:44 UTC, blessMe-Padre commented on catalog.html
> +          <p>Информационный сайтдля туристов</p>
Исправил

2021-05-25 02:57 UTC, blessMe-Padre commented on catalog.html
> +          <h3>Sedona</h3>
Исправил((

2021-05-25 03:00 UTC, blessMe-Padre commented on catalog.html
> +    <section>
В макете 2 страницы и везде футер одинаковый и карта тоже повторяется, и я подумал что карту можно в футер засунуть))

2021-05-25 03:03 UTC, blessMe-Padre commented on catalog.html
> +      <p>NЁRDS DESIGN STUDIO</p>
(просто вставил копипастом)
Исправил

2021-05-25 03:04 UTC, blessMe-Padre commented on index.html
> +            <li><a href="#" class="menu__link menu__link--active">Студия</a></li>
Удалил. Т.к. файл стилей еще не подключен, удалил все классы и лишние обертки

2021-05-25 03:11 UTC, blessMe-Padre commented on index.html
> +        <p>Долго, дорого, скрупулезно.</p>
Исправил

2021-05-25 03:13 UTC, blessMe-Padre commented on index.html
> +            <h3 class="services__title">Веб-сайты</h3>
Спасибо. БЭМ пока тяжело идет(

2021-05-25 03:15 UTC, blessMe-Padre commented on index.html
> +            <a href="#" class="button btn--green">Заказать</a>
button button--green?

2021-05-25 03:16 UTC, blessMe-Padre commented on index.html
> +      <h2 class=".visually-hidden">Производители</h2>
Исправил

2021-05-26 17:07 UTC, mikhin commented on catalog.html
> +      <a href="index.html">
Корзину — точно, логотип — обсуждаемо)

2021-05-26 17:07 UTC, mikhin commented on catalog.html
> +    <section>
Заголовки могут быть и вне section)

2021-05-26 17:08 UTC, mikhin commented on catalog.html
> +    <section>
Ну тоже норм, да)

2021-05-26 17:08 UTC, mikhin commented on index.html
> +            <a href="#" class="button btn--green">Заказать</a>
Ага

2021-05-26 17:08 UTC, mikhin commented on index.html
> +            <h3 class="services__title">Веб-сайты</h3>
Понимаю)

2021-05-26 17:10 UTC, mikhin requested changes

2021-05-26 17:10 UTC, mikhin commented on index.html
> +          <img src="img/slider/nerds-index-slide1.jpg" width="760" height="431" alt="три смартфона">
Давай все ссылки на ресурсы сделаем не относительными, а абсолютными)

2021-05-26 17:10 UTC, mikhin commented on index.html
> +      <img src="img/clients/logo_htmlacademy1.svg" width="199" height="58" alt="логотип html академия">
Для всех файлов нужно какое-то единообразное написение с очень понятными именами. Сейчас файлы названы вразнобой по-разному и у них непонятные имена)

2021-05-29 14:40 UTC, blessMe-Padre commented on index.html
> +          <img src="img/slider/nerds-index-slide1.jpg" width="760" height="431" alt="три смартфона">
Здесь мне нужен пример абсолютного пути. Ведь все хранится локально... (

2021-05-29 14:44 UTC, blessMe-Padre commented on index.html
> +      <img src="img/clients/logo_htmlacademy1.svg" width="199" height="58" alt="логотип html академия">
Имена файлов привел к общему стилю и вроде как максимально логично назвал.

2021-05-30 17:53 UTC, merged