4.19. Стилизация внутренней страницы
htmlacademy-htmlcss/1789677-nerds-31 pull request #4
Opened 2021-06-03 14:54 UTC by blessMe-Padre

2021-06-04 10:33 UTC, mikhin requested changes

2021-06-04 10:33 UTC, mikhin commented on catalog.html
> +                id="filter-suavcartecito">
suavcartecito

это что значит?)

2021-06-04 10:33 UTC, mikhin commented on catalog.html
> +            <h3>a plus</h3>
А это что за заголовок?)

2021-06-04 10:33 UTC, mikhin commented on css/style.css
> -@font-face {
Почему не нужно?)

2021-06-04 10:33 UTC, mikhin commented on css/style.css
> +.filter ul {
Чисто на будущее (но и будет в рамках следующего курса в Академии) — стилизация через селекторы тегов это всегда мегахрупкость, потому что ты жестко прибиваешь гвоздями реализацию в CSS к реализации в HTML: исправишь тег → придется лезть в стили. Не круто.

Самый надеждный и простой способ — использовать ТОЛЬКО классы =)

2021-06-04 10:33 UTC, mikhin commented on css/style.css
> +.catalog span{
Вот тут особенно видно эту проблему)

Плюс код становится нечитабельным, в первую очередь для тебя самого — ставлю корову на то, что через месяц ты забудешь какой span имел ввиду)

2021-06-04 10:33 UTC, mikhin commented on css/style.css
> +
Давай сделаем форматирование всего файла аккуратным и единообразным — удалим лишние строки, лишние пробелы и все такое)

2021-06-04 10:33 UTC, mikhin commented on css/style.css
> +.catalog ul{
Между объявлениями селекторов лучше всегда делать отступ в одну строку)

2021-06-04 10:33 UTC, mikhin commented on css/style.css
> +.catalog ul{
Фигурная скобка прилипла, нужно отлепить)

2021-06-07 09:18 UTC, blessMe-Padre commented on catalog.html
> +                id="filter-suavcartecito">
Сам в шоке) Исправил

2021-06-07 09:31 UTC, blessMe-Padre commented on css/style.css
> -@font-face {
@font-face {
  font-family: "roboto";
  src: url("../fonts/roboto.woff2") format("woff2"), url("../fonts/roboto.woff") format("woff");
  font-weight: 400;
  font-style: normal;
}
Я не правильно понял.

2021-06-07 09:51 UTC, blessMe-Padre commented on css/style.css
> +.filter ul {
К спискам формы добавил класс для стилизации, заодно и марджины с падингами обнулил

2021-06-07 09:55 UTC, blessMe-Padre commented on css/style.css
> +.catalog span{
Исправил

2021-06-07 10:09 UTC, blessMe-Padre commented on css/style.css
> +
прошелся по всему файлу стилей, навел порядок)

2021-06-09 12:13 UTC, mikhin approved these changes

2021-06-09 12:13 UTC, merged